package:
  name: robotraconteur_training_sim
  version: 0.5.0a1

source:
  url: https://github.com/johnwason/robotraconteur_training_sim/archive/88be294c05408aeb0c96945d863ea4b78349cbe5.tar.gz
  sha256: 66995cf97bff59c68a22a8106c6a5707a9e462774c35aeed4532f608b37db157

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - robotraconteur_companion_python
    - python
    - numpy

  run:
    - __unix # [unix]
    - __win # [win]
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - qpsolvers
    - robotraconteur_companion_python
    - python
    - drekar-launch
    - drekar-launch-process
    - menuinst # [win]
    - numpy

build:
  number: 0
  noarch: python

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"