package:
  name: robotraconteur_training_sim
  version: 0.5.0a1

source:
  url: https://github.com/johnwason/robotraconteur_training_sim/archive/9a47a96aaa968fc64ed238d3f65ab01e7f7fb6ee.tar.gz
  sha256: e29a1a20ace473b215af72732f69fc58a41e7fd30f0dba392c6c525ec7b150ff

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - robotraconteur_companion_python
    - python
    - numpy

  run:
    - __unix # [unix]
    - __win # [win]
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - qpsolvers
    - robotraconteur_companion_python
    - python
    - drekar-launch
    - drekar-launch-process
    - menuinst # [win]
    - numpy

build:
  number: 1
  noarch: python

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"