package:
  name: robotraconteur_training_sim
  version: 0.4.0

source:
  git_url: https://github.com/robotraconteur-contrib/robotraconteur_training_sim.git
  git_rev: v0.4.0

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - robotraconteur_companion_python
    - python
    - numpy

  run:
    - __unix # [unix]
    - __win # [win]
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - qpsolvers
    - robotraconteur_companion_python
    - python
    - drekar-launch
    - drekar-launch-process
    - menuinst # [win]
    - numpy

build:
  number: 3
  noarch: python

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"