package:
  name: robotraconteur_training_sim
  version: 0.5.0a1

source:
  url: https://github.com/johnwason/robotraconteur_training_sim/archive/b186db46ed9649f5691cc9b4dcf62246526fb55c.tar.gz
  sha256: cd1409c51ff211ad658cba1f7bcaed2f8b80e47a31242cb8010a2f3719885aa8

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - robotraconteur_companion_python
    - python
    - numpy

  run:
    - __unix # [unix]
    - __win # [win]
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - qpsolvers
    - robotraconteur_companion_python
    - python
    - drekar-launch
    - drekar-launch-process
    - menuinst # [win]
    - numpy

build:
  number: 3
  noarch: python

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"