{% set version = "0.5.0" %}

package:
  name: robotraconteur_training_sim
  version: {{ version }}

source:
  url: https://github.com/robotraconteur-contrib/robotraconteur_training_sim/archive/v{{ version }}.tar.gz
  sha256: 221724808278a2902d38fd9303d38dbd6ebf75130d23dec977ecb30c6b4c22f4

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - robotraconteur_companion_python
    - python
    - numpy

  run:
    - __unix # [unix]
    - __win # [win]
    - robotraconteur
    - robotraconteur_companion
    - gz-sim
    - gz-sim-robotraconteur-plugins
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - qpsolvers
    - robotraconteur_companion_python
    - python
    - drekar-launch
    - drekar-launch-process
    - menuinst # [win]
    - numpy

build:
  number: 3
  noarch: python

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"