github:
  user_or_org: robotraconteur

channels:
  targets:
    - robotraconteur

provider:
  linux: github_actions
  osx: github_actions
  win: github_actions
  linux_aarch64: None
  linux_ppc64le: None

github_actions:
  upload_packages: False
  store_build_artifacts: True