github:
  user_or_org: robotraconteur

provider:
  linux: github_actions
  osx: github_actions
  win: github_actions
  linux_aarch64: None
  linux_ppc64le: None

github_actions:
  upload_packages: True
  store_build_artifacts: True
noarch_platforms:
  - linux_64
  - win_64